# Generated by Django 4.2 on 2023-05-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOfContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forContent', models.CharField(max_length=225)),
                ('title', models.CharField(max_length=550)),
                ('placeId', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='BlogImages/main/'),
        ),
    ]
