# Generated by Django 4.2 on 2023-05-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog_image_news_image_tag_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
    ]
