# Generated by Django 4.2 on 2023-05-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tableofcontent_forcontent_tableofcontent_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableofcontent',
            old_name='title',
            new_name='TOCtitle',
        ),
    ]
