# Generated by Django 4.2 on 2023-05-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_title_tableofcontent_toctitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag'),
        ),
    ]
