# Generated by Django 4.2 on 2023-05-14 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='news',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='video',
            name='referral',
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('alt', models.CharField(blank=True, max_length=25, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('blogObj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='core.blog')),
                ('newsObj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.news')),
                ('videoObj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.video')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='referral',
            field=models.ManyToManyField(blank=True, to='core.referral'),
        ),
        migrations.AddField(
            model_name='news',
            name='referral',
            field=models.ManyToManyField(blank=True, to='core.referral'),
        ),
        migrations.AddField(
            model_name='video',
            name='referral',
            field=models.ManyToManyField(blank=True, to='core.referral'),
        ),
    ]
