# Generated by Django 4.2 on 2023-05-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_redirect',
            field=models.BooleanField(default=False),
        ),
    ]
