# Generated by Django 4.2 on 2023-05-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_video_is_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='redirect_url',
            field=models.URLField(blank=True, help_text="Enter your youtube or other page's url.", null=True),
        ),
    ]
