# Generated by Django 4.2 on 2023-05-24 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ApplicantsProof')),
            ],
        ),
        migrations.CreateModel(
            name='TalentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('talent', models.CharField(max_length=225)),
                ('age', models.IntegerField()),
                ('define_yourself', models.TextField(max_length=300)),
                ('application_deadline', models.DateField()),
                ('applied_date', models.DateField(auto_now=True)),
                ('proof_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proofimages')),
            ],
        ),
    ]
