# Generated by Django 4.2 on 2023-05-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_proofimages_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentapplication',
            name='proof_images',
        ),
    ]
