# Generated by Django 4.2 on 2023-05-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_talentapplication_proof_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofimages',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.talentapplication'),
        ),
    ]
