# Generated by Django 4.2 on 2023-05-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
